import { PROVIDER_IDS } from "./provider";
import { StockInputGroup } from "./types";

const getEnvValue = (key: string, fallback = ""): string => {
  const value = process.env[key];
  return value && String(value).trim() ? String(value).trim() : fallback;
};

export const CONSTANTS = {
  FMP_API_KEY: getEnvValue("FMP_API_KEY", "YOUR_FMP_API_KEY"),
  ALPHA_VANTAGE_API_KEY: getEnvValue("ALPHA_VANTAGE_API_KEY", "YOUR_ALPHA_VANTAGE_API_KEY"),
  SPREADSHEET_ID: getEnvValue("SPREADSHEET_ID", "YOUR_SPREADSHEET_ID")
};

export const STOCKS_AI: StockInputGroup = {
  TARGET_SHEET_NAME: "FIN_DASHBOARD_AV",
  DATA_PROVIDER: PROVIDER_IDS.ALPHA_VANTAGE,
  INPUT_DATA: [
  { 'symbol': 'CRWV', 'industry': 'AI Cloud' },
  { 'symbol': 'IREN', 'industry': 'AI Cloud' },
  { 'symbol': 'NBIS', 'industry': 'AI Cloud' },
  { 'symbol': 'AMD', 'industry': 'Chip Design' },
  { 'symbol': 'ARM', 'industry': 'Chip Design' },
  { 'symbol': 'ASML', 'industry': 'Chip Design' },
  { 'symbol': 'AVGO', 'industry': 'Chip Design' },
  { 'symbol': 'CRDO', 'industry': 'Chip Design' },
  { 'symbol': 'MRVL', 'industry': 'Chip Design' },
  { 'symbol': 'NVTS', 'industry': 'Chip Design' },
  { 'symbol': 'QCOM', 'industry': 'Chip Design' },
  { 'symbol': 'ADI', 'industry': 'Chip Maker' },
  { 'symbol': 'GFS', 'industry': 'Chip Maker' },
  { 'symbol': 'INTC', 'industry': 'Chip Maker' },
  { 'symbol': 'SKYT', 'industry': 'Chip Maker' },
  { 'symbol': 'TSEM', 'industry': 'Chip Maker' },
  { 'symbol': 'TSM', 'industry': 'Chip Maker' },
  { 'symbol': 'TXN', 'industry': 'Chip Maker' },
  { 'symbol': 'UMC', 'industry': 'Chip Maker' },
  { 'symbol': 'AMKR', 'industry': 'Chip OSAT' },
  { 'symbol': 'ASX', 'industry': 'Chip OSAT' },
  { 'symbol': 'ATEYY', 'industry': 'Chip OSAT' },
  { 'symbol': 'COHU', 'industry': 'Chip OSAT' },
  { 'symbol': 'FN', 'industry': 'Chip OSAT' },
  { 'symbol': 'FORM', 'industry': 'Chip OSAT' },
  { 'symbol': 'IMOS', 'industry': 'Chip OSAT' },
  { 'symbol': 'TER', 'industry': 'Chip OSAT' },
  { 'symbol': 'VRT', 'industry': 'DTCR Build' },
  { 'symbol': 'AAON', 'industry': 'DTCR Parts' },
  { 'symbol': 'ANET', 'industry': 'DTCR Parts' },
  { 'symbol': 'COHR', 'industry': 'DTCR Parts' },
  { 'symbol': 'LITE', 'industry': 'DTCR Parts' },
  { 'symbol': 'MOD', 'industry': 'DTCR Parts' },
  { 'symbol': 'NVT', 'industry': 'DTCR Parts' },
  { 'symbol': 'BE', 'industry': 'Energy' },
  { 'symbol': 'CEG', 'industry': 'Energy' },
  { 'symbol': 'D', 'industry': 'Energy' },
  { 'symbol': 'DUK', 'industry': 'Energy' },
  { 'symbol': 'FCEL', 'industry': 'Energy' },
  { 'symbol': 'LEU', 'industry': 'Energy' },
  { 'symbol': 'NEE', 'industry': 'Energy' },
  { 'symbol': 'SMR', 'industry': 'Energy' },
  { 'symbol': 'SO', 'industry': 'Energy' },
  { 'symbol': 'TLN', 'industry': 'Energy' },
  { 'symbol': 'VST', 'industry': 'Energy' },
  { 'symbol': 'MU', 'industry': 'Mem' },
  { 'symbol': 'SNDK', 'industry': 'Mem' },
  { 'symbol': 'AAPL', 'industry': 'Tech' },
  { 'symbol': 'AMZN', 'industry': 'Tech' },
  { 'symbol': 'GOOG', 'industry': 'Tech' },
  { 'symbol': 'META', 'industry': 'Tech' },
  { 'symbol': 'MSFT', 'industry': 'Tech' },
  { 'symbol': 'NVDA', 'industry': 'Tech' },
  { 'symbol': 'AVAV', 'industry': 'Defense' },
  { 'symbol': 'KTOS', 'industry': 'Defense' },
  { 'symbol': 'LMT', 'industry': 'Defense' },
  { 'symbol': 'NOC', 'industry': 'Defense' },
  { 'symbol': 'RTX', 'industry': 'Defense' },
  { 'symbol': 'BRK-B', 'industry': 'Finance' },
  { 'symbol': 'HOOD', 'industry': 'Finance' },
  { 'symbol': 'KLAR', 'industry': 'Finance' },
  { 'symbol': 'MELI', 'industry': 'Finance' },
  { 'symbol': 'SEZL', 'industry': 'Finance' },
  { 'symbol': 'SOFI', 'industry': 'Finance' },
  { 'symbol': 'ABCL', 'industry': 'Health' },
  { 'symbol': 'CRSP', 'industry': 'Health' },
  { 'symbol': 'GH', 'industry': 'Health' },
  { 'symbol': 'GRAL', 'industry': 'Health' },
  { 'symbol': 'HIMS', 'industry': 'Health' },
  { 'symbol': 'ISRG', 'industry': 'Health' },
  { 'symbol': 'JNJ', 'industry': 'Health' },
  { 'symbol': 'LLY', 'industry': 'Health' },
  { 'symbol': 'NVO', 'industry': 'Health' },
  { 'symbol': 'OSCR', 'industry': 'Health' },
  { 'symbol': 'PFE', 'industry': 'Health' },
  { 'symbol': 'TEM', 'industry': 'Health' },
  { 'symbol': 'UTHR', 'industry': 'Health' },
  { 'symbol': 'IONQ', 'industry': 'Quant' },
  { 'symbol': 'QBTS', 'industry': 'Quant' },
  { 'symbol': 'RGTI', 'industry': 'Quant' },
  { 'symbol': 'CRM', 'industry': 'Soft' },
  { 'symbol': 'CRWD', 'industry': 'Soft' },
  { 'symbol': 'FIG', 'industry': 'Soft' },
  { 'symbol': 'INTU', 'industry': 'Soft' },
  { 'symbol': 'NOW', 'industry': 'Soft' },
  { 'symbol': 'PLTR', 'industry': 'Soft' },
  { 'symbol': 'RBRK', 'industry': 'Soft' },
  { 'symbol': 'RDDT', 'industry': 'Soft' },
  { 'symbol': 'ASTS', 'industry': 'Space' },
  { 'symbol': 'LUNR', 'industry': 'Space' },
  { 'symbol': 'MNTS', 'industry': 'Space' },
  { 'symbol': 'RKLB', 'industry': 'Space' },
  { 'symbol': 'NFLX', 'industry': 'Tech' },
  { 'symbol': 'UBER', 'industry': 'Tech' },
  ]
};

export const STOCKS_OTHER: StockInputGroup = {
  TARGET_SHEET_NAME: "FIN_DASHBOARD_FMP",
  DATA_PROVIDER: PROVIDER_IDS.FMP,
  INPUT_DATA: [
  { 'symbol': 'CRWV', 'industry': 'AI Cloud' },
  { 'symbol': 'IREN', 'industry': 'AI Cloud' },
  { 'symbol': 'NBIS', 'industry': 'AI Cloud' },
  { 'symbol': 'AMD', 'industry': 'Chip Design' },
  { 'symbol': 'ARM', 'industry': 'Chip Design' },
  { 'symbol': 'ASML', 'industry': 'Chip Design' },
  { 'symbol': 'AVGO', 'industry': 'Chip Design' },
  { 'symbol': 'CRDO', 'industry': 'Chip Design' },
  { 'symbol': 'MRVL', 'industry': 'Chip Design' },
  { 'symbol': 'NVTS', 'industry': 'Chip Design' },
  { 'symbol': 'QCOM', 'industry': 'Chip Design' },
  { 'symbol': 'ADI', 'industry': 'Chip Maker' },
  { 'symbol': 'GFS', 'industry': 'Chip Maker' },
  { 'symbol': 'INTC', 'industry': 'Chip Maker' },
  { 'symbol': 'SKYT', 'industry': 'Chip Maker' },
  { 'symbol': 'TSEM', 'industry': 'Chip Maker' },
  { 'symbol': 'TSM', 'industry': 'Chip Maker' },
  { 'symbol': 'TXN', 'industry': 'Chip Maker' },
  { 'symbol': 'UMC', 'industry': 'Chip Maker' },
  { 'symbol': 'AMKR', 'industry': 'Chip OSAT' },
  { 'symbol': 'ASX', 'industry': 'Chip OSAT' },
  { 'symbol': 'ATEYY', 'industry': 'Chip OSAT' },
  { 'symbol': 'COHU', 'industry': 'Chip OSAT' },
  { 'symbol': 'FN', 'industry': 'Chip OSAT' },
  { 'symbol': 'FORM', 'industry': 'Chip OSAT' },
  { 'symbol': 'IMOS', 'industry': 'Chip OSAT' },
  { 'symbol': 'TER', 'industry': 'Chip OSAT' },
  { 'symbol': 'VRT', 'industry': 'DTCR Build' },
  { 'symbol': 'AAON', 'industry': 'DTCR Parts' },
  { 'symbol': 'ANET', 'industry': 'DTCR Parts' },
  { 'symbol': 'COHR', 'industry': 'DTCR Parts' },
  { 'symbol': 'LITE', 'industry': 'DTCR Parts' },
  { 'symbol': 'MOD', 'industry': 'DTCR Parts' },
  { 'symbol': 'NVT', 'industry': 'DTCR Parts' },
  { 'symbol': 'BE', 'industry': 'Energy' },
  { 'symbol': 'CEG', 'industry': 'Energy' },
  { 'symbol': 'D', 'industry': 'Energy' },
  { 'symbol': 'DUK', 'industry': 'Energy' },
  { 'symbol': 'FCEL', 'industry': 'Energy' },
  { 'symbol': 'LEU', 'industry': 'Energy' },
  { 'symbol': 'NEE', 'industry': 'Energy' },
  { 'symbol': 'SMR', 'industry': 'Energy' },
  { 'symbol': 'SO', 'industry': 'Energy' },
  { 'symbol': 'TLN', 'industry': 'Energy' },
  { 'symbol': 'VST', 'industry': 'Energy' },
  { 'symbol': 'MU', 'industry': 'Mem' },
  { 'symbol': 'SNDK', 'industry': 'Mem' },
  { 'symbol': 'AAPL', 'industry': 'Tech' },
  { 'symbol': 'AMZN', 'industry': 'Tech' },
  { 'symbol': 'GOOG', 'industry': 'Tech' },
  { 'symbol': 'META', 'industry': 'Tech' },
  { 'symbol': 'MSFT', 'industry': 'Tech' },
  { 'symbol': 'NVDA', 'industry': 'Tech' },
  { 'symbol': 'AVAV', 'industry': 'Defense' },
  { 'symbol': 'KTOS', 'industry': 'Defense' },
  { 'symbol': 'LMT', 'industry': 'Defense' },
  { 'symbol': 'NOC', 'industry': 'Defense' },
  { 'symbol': 'RTX', 'industry': 'Defense' },
  { 'symbol': 'BRK-B', 'industry': 'Finance' },
  { 'symbol': 'HOOD', 'industry': 'Finance' },
  { 'symbol': 'KLAR', 'industry': 'Finance' },
  { 'symbol': 'MELI', 'industry': 'Finance' },
  { 'symbol': 'SEZL', 'industry': 'Finance' },
  { 'symbol': 'SOFI', 'industry': 'Finance' },
  { 'symbol': 'ABCL', 'industry': 'Health' },
  { 'symbol': 'CRSP', 'industry': 'Health' },
  { 'symbol': 'GH', 'industry': 'Health' },
  { 'symbol': 'GRAL', 'industry': 'Health' },
  { 'symbol': 'HIMS', 'industry': 'Health' },
  { 'symbol': 'ISRG', 'industry': 'Health' },
  { 'symbol': 'JNJ', 'industry': 'Health' },
  { 'symbol': 'LLY', 'industry': 'Health' },
  { 'symbol': 'NVO', 'industry': 'Health' },
  { 'symbol': 'OSCR', 'industry': 'Health' },
  { 'symbol': 'PFE', 'industry': 'Health' },
  { 'symbol': 'TEM', 'industry': 'Health' },
  { 'symbol': 'UTHR', 'industry': 'Health' },
  { 'symbol': 'IONQ', 'industry': 'Quant' },
  { 'symbol': 'QBTS', 'industry': 'Quant' },
  { 'symbol': 'RGTI', 'industry': 'Quant' },
  { 'symbol': 'CRM', 'industry': 'Soft' },
  { 'symbol': 'CRWD', 'industry': 'Soft' },
  { 'symbol': 'FIG', 'industry': 'Soft' },
  { 'symbol': 'INTU', 'industry': 'Soft' },
  { 'symbol': 'NOW', 'industry': 'Soft' },
  { 'symbol': 'PLTR', 'industry': 'Soft' },
  { 'symbol': 'RBRK', 'industry': 'Soft' },
  { 'symbol': 'RDDT', 'industry': 'Soft' },
  { 'symbol': 'ASTS', 'industry': 'Space' },
  { 'symbol': 'LUNR', 'industry': 'Space' },
  { 'symbol': 'MNTS', 'industry': 'Space' },
  { 'symbol': 'RKLB', 'industry': 'Space' },
  { 'symbol': 'NFLX', 'industry': 'Tech' },
  { 'symbol': 'UBER', 'industry': 'Tech' },
  ]
};

export const DASHBOARD_CONFIGS: StockInputGroup[] = [STOCKS_AI, STOCKS_OTHER];
