name: Stock Scanner Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  run-stock-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '26.4.0'

      - name: Install dependencies
        run: npm install

      - name: Run stock scanner
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: npm run fetch
